version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_TAG: 3.11
        GH_USER: edg-org
        GH_REPO: edg--template
    ports:
      - "8002:80"
    env_file:
      - api/.env
    restart: on-failure
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: referential_db
      # MYSQL_USER: authuser
      # MYSQL_PASSWORD: authuser
    restart: always
volumes:
  mysql_data:
